/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Clases.*;

import Clases.Funciones_Texto_Objeto;
import static Ventanas.Registro.ObjetosEmpleados;
import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author Alexander Dybala
 */
public class Modificar_Empleado extends javax.swing.JFrame {

    /**
     * Creates new form Modificar_Empleado
     */
    
    public ArrayList listar_empleado = new ArrayList();
    public ArrayList ordenados = new ArrayList();
    public int index;
    private boolean band=false;
    
    
    public Modificar_Empleado() {
        this.setTitle("Proyecto Final");
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    
    public void agregarItemsCombobox()
    {
        /*jTextField1.setText("");
        jTextField2.setText("");
        jTextField5.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");*/
        jComboBox2.removeAllItems();
        ordenados.clear();
        //ordenados.
        Funciones_Texto_Objeto.Leer_Archivo_Objeto(ObjetosEmpleados, "Objeto.bin");
        
        
        System.out.println("FALLO"+ObjetosEmpleados.size());
        for(int i = 0; i < ObjetosEmpleados.size(); i++)
        {
            if(String.valueOf(jComboBox1.getSelectedItem()).equals("Admin Almacen"))
            {
                if( ObjetosEmpleados.get(i).getID()>= 500 && ObjetosEmpleados.get(i).getID()<1000 )
                {
                    ordenados.add(ObjetosEmpleados.get(i).getID());
                }
            }
            else if(String.valueOf(jComboBox1.getSelectedItem()).equals("Admin Ventas"))
            {
                if( ObjetosEmpleados.get(i).getID()>= 1000 && ObjetosEmpleados.get(i).getID() < 1500 )
                {
                    ordenados.add(ObjetosEmpleados.get(i).getID());
                }
            }
            
            else if(String.valueOf(jComboBox1.getSelectedItem()).equals("Admin Produccion"))
            {
                if( ObjetosEmpleados.get(i).getID()>= 1500 )
                {
                    ordenados.add(ObjetosEmpleados.get(i).getID());
                }
            }
        }
        
        
        Collections.sort(ordenados);
        
        //if(!jComboBox2.getSelectedItem().equals(""))
        //{
            
        System.out.println(ordenados.size());
            for(int i = 0; i < ordenados.size(); i++)
            {
                System.out.println(ordenados.get(i));
                jComboBox2.addItem((String.valueOf(ordenados.get(i))));
            }
        //}
    }
    
    
    public void Cambiar_text()
    {
        /*System.out.println("Heyy:"+jComboBox1.getSelectedItem());
        System.out.println("Tamanio: "+ObjetosEmpleados.size());*/
        for(int i = 0; i < ObjetosEmpleados.size(); i++)
        {
            //System.out.println("item: "+jComboBox2.getSelectedItem());
            if(jComboBox2.getSelectedItem().equals(String.valueOf(ObjetosEmpleados.get(i).getID())))
            {
                jTextField1.setText(ObjetosEmpleados.get(i).getNombre());
                jTextField2.setText(ObjetosEmpleados.get(i).getApellidoP());
                jTextField5.setText(ObjetosEmpleados.get(i).getApellidoM());
                jTextField4.setText(ObjetosEmpleados.get(i).getTelefono());
                jTextField6.setText(ObjetosEmpleados.get(i).getSeguro());
                jTextField7.setText(ObjetosEmpleados.get(i).getDireccion());
                jTextField8.setText(String.valueOf(ObjetosEmpleados.get(i).getSalario()));
                jTextField9.setText(String.valueOf(ObjetosEmpleados.get(i).getTurno()));
                jTextField10.setText(ObjetosEmpleados.get(i).getContrasenia());
                index = i;
                //System.out.println(index);
                break;
            }
        }  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 480, 90, 30);

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 0, 20, 20);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 0, 20, 20);

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 480, 60, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione", "Admin Ventas", "Admin Produccion", "Admin Almacen" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 50, 140, 20);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(370, 50, 100, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 80, 130, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 120, 130, 30);

        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(180, 160, 59, 0);

        jLabel1.setText("Elige el empleado a modificar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 160, 30);

        jLabel2.setText("ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 50, 15, 14);

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 90, 60, 14);

        jLabel4.setText("Apellido Materno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 90, 14);

        jLabel5.setText("Apellido Paterno");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 130, 78, 14);

        jButton5.setText("Default");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(200, 480, 90, 30);

        jLabel6.setText("Telefono: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 210, 60, 14);

        jLabel7.setText("Seguro Social");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 250, 90, 14);

        jLabel8.setText("Direccion: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 290, 70, 14);

        jLabel9.setText("Contraseña: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 430, 110, 14);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(180, 160, 130, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 200, 130, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(180, 240, 130, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(180, 280, 130, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(180, 330, 130, 30);

        jLabel10.setText("MODIFICACIÓN DE EMPLEADO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 4, 170, 20);

        jLabel11.setText("Salario:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 340, 90, 14);

        jLabel12.setText("Turno: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 380, 90, 14);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(180, 370, 130, 30);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(180, 420, 130, 30);

        jButton6.setText("Mostrar Informacion");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(330, 210, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    
       public static void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null,mensaje);
    }
       
       
    public void cerrar()
    {
        Object [] opciones ={"SI","NO"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"¿DESEAS SALIR COMPLETAMENTE DEL PROGRAMA?","Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION)
        {
            mensaje("HAS CERRADO SESION");
            dispose();
            Inicio_Sesion inicio = new Inicio_Sesion();
            inicio.setVisible(true);
            
        }   
        else{}
    }
    
    
    public boolean Mesaje__UPADTE()
    {
        Object [] opciones ={"SI","NO"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"¿ESTAS SEGURO QUE DESEAS ACTUALIZAR DATOS DEL EMPLEADO?","Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION)
        {
            mensaje("HAS MODIFICADO LOS VALORES DEL EMPLEADO");
            return true;
        }   
        else{
            return false;
        }
    }
    
    public static void mensaje_confirmacion_UPDATE(String mensaje){
        JOptionPane.showMessageDialog(null,mensaje);
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setExtendedState(Inicio_Sesion.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cerrar();
        //System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Administrador admin_supremo = new Administrador();
        admin_supremo.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Cambiar_text();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(band)
        {
            if(Mesaje__UPADTE())
            {
                System.out.println("HAY VAMOS HAHAHA");
                int id = Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem()));

                //float salario = ;                 
                char turno = jTextField9.getText().charAt(0);
                
                Empleado Remix_Empleado = new Empleado(jTextField1.getText(), jTextField2.getText(), jTextField5.getText(), id, jTextField4.getText(), jTextField6.getText(), jTextField7.getText(), jTextField8.getText(),  20,turno, jTextField10.getText());
                for(int i = 0; i < ObjetosEmpleados.size(); i++)
                {

                    if(jComboBox2.getSelectedItem().equals(String.valueOf(ObjetosEmpleados.get(i).getID())))
                    {
                        System.out.println("HEYYY!!!! QUE ONDA");
                        ObjetosEmpleados.set(i, Remix_Empleado);
                        Funciones_Texto_Objeto.Update_Archivo(ObjetosEmpleados, "Objeto.bin");
                        break;
                    }
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        /*if(jComboBox2.getSelectedItem().equals("Admin Ventas") || jComboBox2.getSelectedItem().equals("Admin Produccion") || jComboBox2.getSelectedItem().equals("Admin Almacen"))
        {
            
        }*/
        /*sif(!jComboBox2.equals(""))
        {
            Cambiar_text();
        }
        */
        band = false;
 
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        agregarItemsCombobox();
        band= false;
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Cambiar_text();
        band = true;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
