/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;


import Clases.*;
import static Ventanas.Registro.mensaje;
import java.util.*;
import java.util.Collections;
import javax.swing.JOptionPane;
/**
 *
 * @author Estudiante
 */
public class Produccion extends javax.swing.JFrame {

    
    public ArrayList<String> productos = new ArrayList<String>();
    public ArrayList<Pedido> pedidos = new ArrayList<Pedido>();
    public ArrayList pedidos_ordenados = new ArrayList();
    public int index;
    /**
     * Creates new form Produccion
     */
    public Produccion() {
        this.setTitle("Proyecto Final");
        initComponents();
        this.setLocationRelativeTo(null);
        productos.add("PLASTICO BIC");
        productos.add("PRINT PLASTICO");
        //Pedido nuevo_pedido = new Pedido
        agregarItemsCombobox();
    }

    
    public void agregarItemsCombobox()
    {
        
        jComboBox1.removeAll();
        
        //Pedido nuevo_pedido = new Pedido(1, "CHUCHITA", productos, "CUBETA", "ACOM", "12/45/2018", (float) 15.00);
        //pedidos.add(nuevo_pedido);
        Funciones_Pedido.Leer_Archivo_Pedido(pedidos, "Objetos_Pedido.bin");
        for(int i = 0; i < pedidos.size(); i++)
        {
            pedidos_ordenados.add(i,pedidos.get(i).getID());
        }
        Collections.sort(pedidos_ordenados);
        System.out.println(pedidos.size());
        for(int i = 0; i < pedidos.size(); i++)
        {
            jComboBox1.addItem((String.valueOf(pedidos_ordenados.get(i))));
        }
        
    }
    
    
    public void mostrar_Pedido()
    {
        ArrayList<String> productos;
        for(int i = 0; i < pedidos.size(); i++)
        {
            if(jComboBox1.getSelectedItem().equals(String.valueOf(pedidos.get(i).getID())))
            {
                jTextArea1.setText(""); 
                jTextField1.setText(String.valueOf(pedidos.get(i).getID()));
                jTextField2.setText(pedidos.get(i).getNombre());
                jTextField4.setText(pedidos.get(i).getContenedor());
                jTextField5.setText(pedidos.get(i).getFecha());
                jTextField6.setText(String.valueOf(pedidos.get(i).getCuota()));
                productos = pedidos.get(i).obtener_productos();
                //pedidos.get(i).imprimir();
                System.out.println("Tam_pedidos: "+pedidos.get(i).getTamPedidos());
                for(int p=0; p < pedidos.get(i).getTamPedidos(); p++)
                {
                    System.out.println("MAS Y MAS");
                    jTextArea1.append(productos.get(p));
                    jTextArea1.append("\n");
                }
                index = i;
                System.out.println(index);
                break;
            }
        }  
        
    }
    
      
    
    public void Update_Datos()
    {
        
        for (int i = 0; i < pedidos.size(); i++) 
        {
            if(!jComboBox2.getSelectedItem().equals("---Selecciona"))
            {
                pedidos.get(i).setEstado(String.valueOf(jComboBox2.getSelectedItem()));
                break;
            }
        }
        
        Funciones_Pedido.Update_Archivo(pedidos, "Objetos_Pedido.bin");
        
    }
    
    
    
    public void Cambiar_text()
    {
        /*System.out.println("Heyy:"+jComboBox1.getSelectedItem());
        System.out.println("Tamanio: "+ObjetosEmpleados.size());*/
        for(int i = 0; i < pedidos.size(); i++)
        {
            //System.out.println("item: "+jComboBox2.getSelectedItem());
            if(jComboBox2.getSelectedItem().equals(String.valueOf(pedidos.get(i).getID())))
            {
               
                index = i;
                //System.out.println(index);
                break;
            }
        }  
    }
    
    
    
    
    public boolean Mesaje__UPADTE()
    {
        Object [] opciones ={"SI","NO"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"¿ESTAS SEGURO QUE DESEAS ACTUALIZAR DATOS DEL PEDIDO?","Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION)
        {
            mensaje("HAS MODIFICADO LOS VALORES DEL PEDIDO");
            return true;
        }   
        else{
            return false;
        }
    }
    
    public static void mensaje_confirmacion_UPDATE(String mensaje){
        JOptionPane.showMessageDialog(null,mensaje);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("Produccion");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 10, 80, 14);

        jLabel2.setText("Gestionar Proceso");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 30, 110, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Selecione---" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(20, 60, 120, 20);

        jButton1.setText("Default");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 260, 70, 30);

        jButton2.setText("Hacer Cambios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 330, 120, 30);

        jLabel4.setText("Seleccione ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 40, 70, 20);

        jLabel5.setText("ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 80, 20, 14);

        jLabel3.setText("Nombre del cliente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 120, 110, 20);

        jLabel6.setText("Fecha de entrega:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 240, 110, 20);

        jLabel7.setText("Estado:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 160, 50, 20);

        jLabel8.setText("Contenedor: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 200, 80, 20);

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 70, 110, 30);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 110, 110, 30);

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(230, 190, 110, 30);

        jTextField5.setEditable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(230, 230, 110, 30);

        jLabel9.setText("Productos");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 80, 80, 14);

        jLabel10.setText("Cuota Total:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 274, 90, 20);

        jTextField6.setEditable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(230, 270, 110, 30);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 100, 220, 140);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Selecciona", "PROCESO", "TERMINADO" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(230, 150, 110, 30);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CERRAR SESIO");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 330, 70, 30);

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(580, 10, 20, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(Mesaje__UPADTE())
        {
            Update_Datos();
            Funciones_Pedido.Iprimir(pedidos);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        mostrar_Pedido();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Inicio_Sesion sesion = new Inicio_Sesion();
        sesion.setVisible(true);
        //System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setExtendedState(Inicio_Sesion.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
