/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import java.util.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexander
 */
public class Venta_Almacen extends javax.swing.JFrame {

    
    public static ArrayList<String> arreglo_matriculas=new ArrayList<String>();
    public static ArrayList<String> arreglo_nombres=new ArrayList<String>();
    public static int auxiliar=0;
    /**
     * Creates new form Indicaciones_2
     */
    
    
    
    public Venta_Almacen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    public void cerrar(String mensaje){
        Object [] opciones ={"SI","NO"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,mensaje,"Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION)
        {
            dispose();
            Inicio_Sesion regresoInterfaz2 = new Inicio_Sesion();
            regresoInterfaz2.setVisible(true);
            mensaje("HAS CERRADO SESION");
        }
        else{}
    }
    
    public void cerrar(){
    Object [] opciones ={"SI","NO"};
    int eleccion = JOptionPane.showOptionDialog(rootPane,"¿DESEAS SALIR COMPLETAMENTE DEL PROGRAMA?","Mensaje de Confirmacion",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
    if (eleccion == JOptionPane.YES_OPTION)
    {
        System.exit(0);
        //mensaje("HAS CERRADO SESION");
    }
    else{}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBienvenido = new javax.swing.JLabel();
        jLabelP1 = new javax.swing.JLabel();
        jLabelL1 = new javax.swing.JLabel();
        jLabelL2 = new javax.swing.JLabel();
        jLabelL3 = new javax.swing.JLabel();
        jLabelL4 = new javax.swing.JLabel();
        jLabelL5 = new javax.swing.JLabel();
        jLabelL6 = new javax.swing.JLabel();
        jLabelL7 = new javax.swing.JLabel();
        jLabelL8 = new javax.swing.JLabel();
        jLabelL9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 490));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabelBienvenido.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabelBienvenido.setText("BIENVENIDO");
        getContentPane().add(jLabelBienvenido);
        jLabelBienvenido.setBounds(360, 10, 99, 25);

        jLabelP1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelP1.setText(" Para realizar el siguiente cuestionario deberás tomar en cuenta las siguientes");
        getContentPane().add(jLabelP1);
        jLabelP1.setBounds(10, 37, 537, 22);

        jLabelL1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelL1.setText("dos, las cuales abarcarán los siguientes temas.");
        getContentPane().add(jLabelL1);
        jLabelL1.setBounds(20, 126, 332, 22);

        jLabelL2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelL2.setText("        i)      Conceptos de Programación Orientada a Objetos.");
        getContentPane().add(jLabelL2);
        jLabelL2.setBounds(10, 154, 404, 22);

        jLabelL3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelL3.setText("        ii)     Excepciones en Java.");
        getContentPane().add(jLabelL3);
        jLabelL3.setBounds(10, 182, 205, 22);

        jLabelL4.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelL4.setText("        iii)    Creación de archivos en Java.");
        getContentPane().add(jLabelL4);
        jLabelL4.setBounds(10, 210, 263, 22);

        jLabelL5.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelL5.setText("        iv)     Creación de interfaces en Java.");
        getContentPane().add(jLabelL5);
        jLabelL5.setBounds(10, 238, 276, 22);

        jLabelL6.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelL6.setText("   2) Deberás seleccionar con el click izquierdo del cursor la opción que consideres correcta.");
        getContentPane().add(jLabelL6);
        jLabelL6.setBounds(10, 266, 619, 22);

        jLabelL7.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelL7.setText("   3) Da click izquierto en el botón \"Siguiente\" para avanzar a la siguiente pregunta.");
        getContentPane().add(jLabelL7);
        jLabelL7.setBounds(10, 294, 563, 22);

        jLabelL8.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelL8.setText("   4) Cuando el exámen acabe da click izquierdo en \"guardar registro y salir\" para salvar tu puntuación y");
        getContentPane().add(jLabelL8);
        jLabelL8.setBounds(10, 322, 703, 22);

        jLabelL9.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelL9.setText("       tiempo en tu récord o solo \"salir\" para no guardar tus resultados en tu récord.");
        getContentPane().add(jLabelL9);
        jLabelL9.setBounds(10, 350, 555, 22);

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel1.setText("                               A continuación da click izquierdo con tu cursor para comenzar prueba.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 390, 603, 22);

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel2.setText("                                                                        ¡¡¡EXITO!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(79, 418, 359, 22);

        jButton1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 11)); // NOI18N
        jButton1.setText("COMENZAR PRUEBA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 440, 248, 23);

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 0, 20, 20);

        jButton3.setBackground(new java.awt.Color(51, 0, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(760, 0, 20, 20);

        jButton4.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 11)); // NOI18N
        jButton4.setText("CERRAR SESION");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 440, 140, 23);

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel3.setText(" indicaciones para podercontestarlo adecuadamente.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 360, 22);

        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel4.setText("   1) A continuación se te presentarán 10 preguntas de tipo opción múltiple sobre tu cursor de programación ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 98, 735, 22);

        jButton5.setText("VER RECORDS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(260, 440, 210, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/F1.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, -10, 820, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Indicaciones_2.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null,mensaje);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cerrar();
        //System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         setExtendedState(Venta_Almacen.CROSSHAIR_CURSOR); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cerrar("¿DESEAS SALIR DEL EXAMEN?");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta_Almacen().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelL1;
    private javax.swing.JLabel jLabelL2;
    private javax.swing.JLabel jLabelL3;
    private javax.swing.JLabel jLabelL4;
    private javax.swing.JLabel jLabelL5;
    private javax.swing.JLabel jLabelL6;
    private javax.swing.JLabel jLabelL7;
    private javax.swing.JLabel jLabelL8;
    private javax.swing.JLabel jLabelL9;
    private javax.swing.JLabel jLabelP1;
    // End of variables declaration//GEN-END:variables
}
